name: CURL CLI ACTION
on:
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: pulling file
      run: |
        curl http://www.baidu.com
        git clone https://gitlab.com/crypto-chess/crypto-chess.git
        ls
        cd new-machine
        ls
