name: CURL CLI ACTION
on:
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: pulling file
      run: | 
        git clone ${{secrets.new_machine}}
        cd new-machine
        curl ${{secrets.new_machine_config_file}} > config.yaml
        git config user.name 'onedayrex'
        git config user.email 'onedayrex'
        git add .
        git commit -m "update config"
        git status
        git push
